import { readFile } from "fs/promises";
import { parseCsv } from "../index.js";

import "dotenv/config.js";

const loadCsvWithHeaders = async () => {
    let importedCsv: string;
    try {
        importedCsv = await readFile("./testData/zillow.csv", 'utf8')
    } catch {
        throw new Error('Failed to load the CSV file.');
    }

    if (!importedCsv) return null;

    const parsedCsv = await parseCsv({ csv: importedCsv, hasColumnHeaders: true, workbookName: 'Zillow', sheetName: 'coolSheet#1', flatfileKey: process.env?.flatfile ?? '' })
    console.log(parsedCsv)
}

// const loadCsvWithoutHeaders = async () => {
//     let importedCsv: string;
//     try {
//         importedCsv = await readFile("./testData/example.csv", 'utf8')
//     } catch {
//         throw new Error('Failed to load the CSV file.');
//     }

//     if (!importedCsv) return null;

//     const parsedCsv = parseCsv({ csv: importedCsv, hasColumnHeaders: false, columnHeaders: ['date', 'measurementTotal', 'measurement', 'product', 'name', 'deliveryPoint'] })
//     console.log('parsedCsv', parsedCsv)
// }

// const loadCsvWithAutoGeneratedHeaders = async () => {
//     // eslint-disable-next-line no-undef
//     // const env: string = process.env.flatfile as string;
//     // flatfileKey
//     let importedCsv: string;
//     try {
//         importedCsv = await readFile("./testData/example.csv", 'utf8')
//     } catch {
//         throw new Error('Failed to load the CSV file.');
//     }

//     if (!importedCsv) return null;

//     const parsedCsv = parseCsv({ csv: importedCsv, hasColumnHeaders: false })
// }


loadCsvWithHeaders()
// loadCsvWithoutHeaders()
// loadCsvWithAutoGeneratedHeaders()